### ISSUE TITLE
Striped Table

### ISSUE THREAD

**Issue by ghost** [pure-css/pure#105]
When using a striped table, you can set the background of the row by adding the pure-table-odd class. `<tr class="pure-table-odd">`.

This is a little annoying when iterating over rows from database and showing them in a striped table as you have to use a counter with a conditional to add the class `pure-table-odd` to odd rows. If you use `n-th child(odd)` you can automatically change the background colour of odd rows without the need for a class.

``` css
table.striped tr:nth-child(odd) td {
    background: #F2F2F2;
}
```

http://www.w3.org/Style/Examples/007/evenodd.en.html
