### ISSUE TITLE
label-element might turn into a blocked element

### ISSUE THREAD

**Issue by ItsAsbreuk** [pure-css/pure#161]
When having a label that has a div inside, then Safari on OS-X treats the label as a 'block-element'. This is strange, because it seems only to happen when there is a div-element inside the label.

You can see this happening at http://purecss.io/forms/ taking the inline-form example. Just replace

``` html
<input id="remember" type="checkbox">
```

with 

``` html
<div id="remember"></div>
```

The problem is solved when changing the css

``` css
.pure-form label {
    margin: 0.5em 0 0.2em;
    font-size: 90%;
}
```

into

``` css
.pure-form label {
    margin: 0.5em 0 0.2em;
    font-size: 90%;
    display: inline-block;
    *display: inline;
}
```

I've seen this effect only with safari.

Best Regards,
Marco.
