### ISSUE TITLE
Horizontal menu should not have a fixed height on the UL

### ISSUE THREAD

**Issue by jconniff** [pure-css/pure#164]
These comments are about horizontal menus, not vertical menus.

in menus-core.css 
line 60
There is a fixed height given to the ul. I don't believe this should be done.

``` css
.pure-menu.pure-menu-horizontal > ul {
    display: inline-block;
    *display: inline;
    zoom: 1;
    vertical-align: middle;
    height: 2.4em;  /* I believe this should not be here */
}
```

This becomes a problem when the developer wants a menu background color that is different than the page background (a common case). A couple pixels of menu background color shows under the selected menu item. 

![pure_menu_ul_height](https://f.cloud.github.com/assets/449779/965062/2640e0b0-0523-11e3-80a4-665d73d95e6d.png)

and/or if the developer wants to customize the padding of the menu items
![pure_menu_ul_height_2](https://f.cloud.github.com/assets/449779/965047/e9a13c7c-0522-11e3-8e57-7afe5e19b41e.png)
