### ISSUE TITLE
.pure-form-aligned textarea --> vertical align not on top?

### ISSUE THREAD

**Issue by ItsAsbreuk** [pure-css/pure#174]
You might not agree, or it was a slip of the pen.
However, I feel that the next css

``` css
.pure-form-aligned textarea {
    vertical-align: middle;
}
```

should change into:

``` css
.pure-form-aligned textarea {
    vertical-align: top;
}
```

That is, only for textarea's. When you have a big sized textarea, it is awful to find its label somewhere in the middle. But it's a matter of taste.

Best Regards,
Marco.
