### ISSUE TITLE
Hidden formelements don't hide

### ISSUE THREAD

**Issue by ItsAsbreuk** [pure-css/pure#177]
When form elements are hidden (by node-attribute hidden="hidden", then they ought to be invisible by the rule

``` css
pure [hidden] {
    display: none;
}
```

However, this is overruled by https://github.com/yui/pure/blob/master/src/forms/css/forms.css#L18

which makes the formelements visible again.

Regards,
Marco.
