### ISSUE TITLE
Add sevenths to grid units. (pure-u-1-7)

### ISSUE THREAD

**Issue by dannyfritz** [pure-css/pure#209]
I was creating a calendar and was trying to use pure-u-1-7. I noticed there wasn't one and looked to the grid builder, but it seems like the CSS it creates might be outdated.

Opening this up as a discussion. :speech_balloon: 

For anyone wanting to do this currently, I have created a gist to add to your CSS for sevenths: https://gist.github.com/dannyfritz/6795026

This doesn't add all the other increments (2/7, 3/7, etc.) that would come with adding it to the library.

``` css
.pure-u-1-7 {
    display: inline-block;
    *display: inline; /* IE < 8: fake inline-block */
    zoom: 1;
    letter-spacing: normal;
    word-spacing: normal;
    vertical-align: top;
    text-rendering: auto;
}

.pure-u-1-7 {
    width: 14.2857%;
    *width: 14.2557%%;
}
```
