### ISSUE TITLE
Horizontal menus are not fully responsive

### ISSUE THREAD

**Issue by ItsAsbreuk** [pure-css/pure#250]
When you look at http://purecss.io/layouts/marketing/ and make the screen very small, you see why. Because:

``` css
.pure-menu.pure-menu-horizontal > ul {
    display: inline-block;
    height: 2.4em;
    vertical-align: middle;
}
```

supposes the ul to stay at 2.4em height, which is not apropriate when the li-elements are spread across multiple lines. Eliminating the height -in the marketing example- doesn't work either for the adjecent elements aren't shifted.
