### ISSUE TITLE
Update Pure class names for easy integration with preprocessors

### ISSUE THREAD

**Issue by tilomitra** [pure-css/pure#298]
## Overview

The following is a proposal to update Pure's class name structure so that developers that use preprocessors can easily `@extend` Pure class names in their CSS. 
### Benefits
- Take advantage of the `@extend` directive that exists in preprocessors (LESS, Sass, Stylus, Rework all support extending class names).
- If you're using a preprocessor, you can easily extend Pure components, and keep Pure class names out of your HTML
- Keeps your CSS clean, keeps your HTML class-list clean.
## Example of how this would work

This change would make it possible to do things like this:

**pure.css source code snippet**:

``` css
.p-table {
    /* Remove spacing between table cells (from Normalize.css) */
    border-collapse: collapse;
    border-spacing: 0;
    empty-cells: show;
    border: 1px solid #cbcbcb;
}

.p-th,
.p-td {
    background-color: transparent;
    border-left: 1px solid #cbcbcb;/*  inner column border */
    border-width: 0 0 0 1px;
    font-size: inherit;
    margin: 0;
    overflow: visible; /*to make ths where the title is really long work*/
    padding: 6px 12px; /* cell padding */
}

.p-is-first-cell {
    border-left-width: 0;
}


.p-thead {
    background: #e0e0e0;
    color: #000;
    text-align: left;
    vertical-align: bottom;
}

/* HORIZONTAL BORDERED TABLES */
.p-table-horizontal .p-td {
    border-width: 0 0 1px 0;
    border-bottom: 1px solid #cbcbcb;
}
.p-table-horizontal tbody > tr:last-child .p-td {
    border-bottom-width: 0;
}
...
```

**app.scss**:

``` css
@import "pure"

.my-table
    @extend .p-table
    @extend .p-table-horizontal

.my-thead
    @extend .p-thead
    background: #111
    color: #eee

.my-cell
    @extend .p-td
    background: #eee
```

**index.html**:

``` html
<table class="my-table">
        <thead class="my-thead">
            <tr>
                <th class="p-th">#</th>
                <th class="p-th">Make</th>
                <th class="p-th">Model</th>
                <th class="p-th">Year</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td class="my-cell">1</td>
                <td class="my-cell">Honda</td>
                <td class="my-cell">Accord</td>
                <td class="my-cell">2009</td>
            </tr>
            ...
```

**Looks like this:**
Despite not having any pure class names in your HTML, you were able to extend the Pure classes and create a customized horizontally-bordered table.

![](http://f.cl.ly/items/2B0g0G2T1M412j003e04/Screen%20Shot%202014-02-15%20at%201.29.46%20PM.png)
## Class Naming Convention
- **MODULE** class names must always have the format `.p-[module]`.
- **SUB-MODULE** class names must always have the format `.p-[module]-[submodule]`.
- **STATE** class names must always have the format `.p-is-[state]-[module]`. The state should be in past tense if it is referring to a pseudo-state. (ie: `.p-btn:hover` => `.p-is-hovered-btn`)
  - Follow the following naming conventions for common pseudo-selectors:
    - `.p-foo:hover` => `.p-is-hovered-foo`
    - `.p-foo:active` => `.p-is-pressed-foo`
    - `.p-foo:focus` => `.p-is-focussed-foo`
- It's important to understand the difference between **SUB-MODULE** classes and **STATE** classes.
  - Use a sub-module class name to denote permanent stylistic changes (ie: .`.p-form-stacked` vs `.p-form` or `.p-btn-primary` vs `.p-btn`).
  - Use a state class name to denote a state that can be added/removed with JS or user-interaction. (ie: `.p-is-active-btn` vs `.p-btn`).
- Not everything needs to be a single-level class name. Create a single class name if it's something that the user will want to modify.
- Every single-level class name is assumed to be `@extend`ible. `@extend`ing these class names means that their child selector rules will also be applied.
- Every pseudo selector must have an accompanying class name so it can be hooked onto during `@extend`. Generally, pseudo-selectors should have an accompanying **STATE** class name (since pseudo-selectors imply temporary user-interaction (`:hover`, `:active`).
- Every attribute selector must have an accompanying class name so it can be hooked onto during `@extend`. Generally, attribute selectors should have an accompanying **STATE** class name (since attributes are often manipulated using JavaScript).
## Base
- Nothing changes.
## Grids
- Nothing changes.
## Forms
- .p-form
- .p-form-stacked
- .p-form-aligned
- .p-input (all texty inputs)
  - .p-is-focussed-input
  - .p-is-disabled-input
  - .p-is-readonly-input
  - .p-is-invalid-input
- .p-checkbox
- .p-radio
- .p-label
- .p-fieldset
- .p-legend
- .p-message
## Tables
- .p-table
- .p-caption
- .p-thead
- .p-th
  -  .p-is-first-th
- .p-td
  - .p-is-first-td
- .p-table-bordered
- .p-table-horizontal
- .p-table-striped
## Buttons
- .p-btn
- .p-btn-primary
- .p-btn-selected
- .p-is-hovered-btn
- .p-is-focussed-btn
- .p-is-pressed-btn
- .p-is-disabled-btn
- .p-is-hidden-btn
## Menus

_This is based on the new responsive menus_
- .p-menu
- .p-menu-horizontal
- .p-menu-fixed
- .p-menu-separator
- .p-menu-responsive
- .p-menu-toggle
- .p-menu-list
- .p-menu-list-item
- .p-menu-heading
- .p-menu-link
  - .p-is-selected-menu-link
  - .p-is-hovered-menu-link
  - .p-is-focussed-menu-link
  - .p-is-disabled-menu-link
## Paginator

_Let's get rid of it._
## Feedback Welcome

This is very much a WIP, so feedback is welcome. I'd especially like to hear from folks who use preprocessors. Would this make life easier for you?
