### ISSUE TITLE
Add support for vertical align columns

### ISSUE THREAD

**Issue by walkerab** [pure-css/pure#335]
I would like to be able to vertically align my `pure-u` columns.

I've tried adding classes to my columns:

``` css
.u-align-end {
    vertical-align: bottom; /* for the display-inline fallback */
    align-self: end; /* for flex-box 2012 standard */
    align-self: flex-end; /* for flex-box latest standard */
}

.u-align-center {
    ...
}
```

But they don't work in Safari, since it is doing strange things with `display: -webkit-flex` on `.pure-g`. I could simply remove `display: -webkit-flex`, but then I'm worried I might be breaking compatibility elsewhere. I don't have a Windows machine to test on.

It would be great if this functionality could be built into Pure. IMO one of the key reasons to use inline-block/flex-box over floats is the ability to align columns.
#293, #190 seem related.
