### ISSUE TITLE
why pure-menu ul ? and not pure-menu > ul ?

### ISSUE THREAD

**Issue by darkyen** [pure-css/pure#358]
Was this intended ?

``` css
.pure-menu ul {
    left: -10000px;
    list-style: none;
    margin: 0;
    padding: 0;
    top: -10000px;
    z-index: 1;
}
.pure-menu ul {
    position: absolute;
    visibility: hidden;
}
```
