### ISSUE TITLE
pure form select tag - lowercase letters descenders cut off 

### ISSUE THREAD

**Issue by edwardhew** [pure-css/pure#459]
On Windows 8.1, Firefox (36.0.1 / latest), HTML select tag element.

In the purecss site, US state names are in full uppercase, this isn't an issue, but lowercase letters will have their descenders cut off, example: "Play" looks like "Plav" because the lower case y's descender is cut off.

Found its because of this.

``` css
.pure-form select {
    height: 2.25em;
}
```
