### ISSUE TITLE
box-sizing in base css

### ISSUE THREAD

**Issue by allanesquina** [pure-css/pure#522]
Hi, do you agree that box-sizing: border-box should be in base.css file? 
It's repeated in some files. I think it's important for other elements like menu as well.
Maybe adding this code in the base.css file and removing from the others.

``` css
*, *:before, *:after {
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
}
```

Good reference:
https://css-tricks.com/box-sizing/

:+1:
