### ISSUE TITLE
Grid bug in Firefox

### ISSUE THREAD

**Issue by Gaubee** [pure-css/pure#60]
when debug in Firefox,something wrong in grid model.
the Firefox's userAgent is is "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:21.0) Gecko/20100101 Firefox/21.0"

for example:

``` css
.pure-u-1-3 {
    width: 33.3333%;
}
```

shold be change like this:

``` css
.pure-u-1-3 {
    width: 33.33%;
}
```

Otherwise it will show to the next line.
