### ISSUE TITLE
select2 styling

### ISSUE THREAD

**Issue by lkraav** [pure-css/pure#700]
### Description

https://github.com/select2/select2 is one of the most popular enhanced select input implementations in the world. Pure CSS could have compatible styling available out of the box to ease development and make things look uniform.

Thoughts or straight to PR? :)

**Comment by lkraav** [comment]
Initial idea

```css
[class^="select2"] { font-family: $font-pure-stack; }                                                                                                                               
                                                                                                                                                                                  
.select2 {                                                                                                                                                                        
                                                                                                                                                                                  
    &-results__option { padding-left: $pure-input-padding-h; padding-right: @padding-left; }                                                                                      
                                                                                                                                                                                  
    &-search input { padding: $pure-input-padding !important; }                                                                                                                   
                                                                                                                                                                                  
    &-selection { height: auto; margin-bottom: 0 /* select2.css */;                                                                                                               
                                                                                                                                                                                  
        &__arrow { bottom: 0; margin: auto; top: 0; }                                                                                                                             
                                                                                                                                                                                  
        &__rendered { line-height: normal; min-height: 1em; padding-bottom: $pure-input-padding-v; padding-left: $pure-input-padding-h /* pure */; padding-top: @padding-bottom; }
                                                                                                                                                                                  
    }                                                                                                                                                                             
                                                                                                                                                                                  
}
```
